using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Payroll
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            comboBox1.Items.Add("January 2014");
            comboBox1.Items.Add("February 2014");
            comboBox1.Items.Add("March 2014");
            comboBox1.Items.Add("Aril 2014");
            comboBox1.Items.Add("May 2014");
            comboBox1.Items.Add("June 2014");
            comboBox1.Items.Add("July 2014");
            comboBox1.Items.Add("August 2014");
            comboBox1.Items.Add("September 2014");
            comboBox1.Items.Add("October 2014");
            comboBox1.Items.Add("November 2014");
            comboBox1.Items.Add("December 2014");

        }              
        private void button3_Click(object sender, EventArgs e)
        {
            comboBox1.Text = comboBox1.Text;
            string Date = comboBox1.Text;
            textBox1.Text = textBox1.Text;
            string Name = textBox1.Text;

            if (Name == "-Enter your name-")
                MessageBox.Show("You must enter your name!", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            if (Name == "")
                MessageBox.Show("You must enter your name!", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);

            if (Date == "-Select a Month-")
                MessageBox.Show("You must set a date first!", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);

            Double HR, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, D17, D18, D19, D20, D21, D22, D23, D24, D25, D26, D27, D28, D29, D30, D31, HRD1, HRD2, HRD3, HRD4, HRD5, HRD6, HRD7, HRD8, HRD9, HRD10, HRD11, HRD12, HRD13, HRD14, HRD15, HRD16, HRD17, HRD18, HRD19, HRD20, HRD21, HRD22, HRD23, HRD24, HRD25, HRD26, HRD27, HRD28, HRD29, HRD30, HRD31 , TH , TH1, TS1, TS2, TS;
            
            HR = Double.Parse(textBox2.Text);
            D1 = Double.Parse(textBox3.Text);
            D2 = Double.Parse(textBox4.Text);
            D3 = Double.Parse(textBox5.Text);
            D4 = Double.Parse(textBox6.Text);
            D5 = Double.Parse(textBox7.Text);
            D6 = Double.Parse(textBox8.Text);
            D7 = Double.Parse(textBox9.Text);
            D8 = Double.Parse(textBox10.Text);
            D9 = Double.Parse(textBox11.Text);
            D10 = Double.Parse(textBox12.Text);
            D11 = Double.Parse(textBox13.Text);
            D12 = Double.Parse(textBox14.Text);
            D13 = Double.Parse(textBox15.Text);
            D14 = Double.Parse(textBox16.Text);
            D15 = Double.Parse(textBox17.Text);
            D16 = Double.Parse(textBox18.Text);
            D17 = Double.Parse(textBox19.Text);
            D18 = Double.Parse(textBox20.Text);
            D19 = Double.Parse(textBox21.Text);
            D20 = Double.Parse(textBox22.Text);
            D21 = Double.Parse(textBox23.Text);
            D22 = Double.Parse(textBox24.Text);
            D23 = Double.Parse(textBox25.Text);
            D24 = Double.Parse(textBox26.Text);
            D25 = Double.Parse(textBox27.Text);
            D26 = Double.Parse(textBox28.Text);
            D27 = Double.Parse(textBox29.Text);
            D28 = Double.Parse(textBox30.Text);
            D29 = Double.Parse(textBox31.Text);
            D30 = Double.Parse(textBox32.Text);
            D31 = Double.Parse(textBox33.Text);           
            TH = Double.Parse(textBox35.Text);


            HRD1 = HR * D1;
            HRD2 = HR * D2;
            HRD3 = HR * D3;
            HRD4 = HR * D4;
            HRD5 = HR * D5;
            HRD6 = HR * D6;
            HRD7 = HR * D7;
            HRD8 = HR * D8;
            HRD9 = HR * D9;
            HRD10 = HR * D10;
            HRD11 = HR * D11;
            HRD12 = HR * D12;
            HRD13 = HR * D13;
            HRD14 = HR * D14;
            HRD15 = HR * D15;
            HRD16 = HR * D16;
            HRD17 = HR * D17;
            HRD18 = HR * D18;
            HRD19 = HR * D19;
            HRD20 = HR * D20;
            HRD21 = HR * D21;
            HRD22 = HR * D22;
            HRD23 = HR * D23;
            HRD24 = HR * D24;
            HRD25 = HR * D25;
            HRD26 = HR * D26;
            HRD27 = HR * D27;
            HRD28 = HR * D28;
            HRD29 = HR * D29;
            HRD30 = HR * D30;
            HRD31 = HR * D31;
            
            
            TS1 =  HRD1 + HRD2 + HRD3 + HRD4 + HRD5 + HRD6 + HRD7 + HRD8 + HRD9 + HRD10 + HRD11 + HRD12 + HRD13 + HRD14 + HRD15 + HRD16 + HRD17 + HRD18 + HRD19 + HRD20 + HRD21 + HRD22 + HRD23 + HRD24 + HRD25 + HRD26 + HRD27 + HRD28 + HRD29 + HRD30 + HRD31;
            TS2 = HR * TH;
            TS = TS1 + TS2;
            TH1 = TH + D1 + D2 + D3 + D4 + D5 + D6 + D7 + D8 + D9 + D10 + D11 + D12 + D13 + D14 + D15 + D16 + D17 + D18 + D19 + D20 + D21 + D22 + D23 + D24 + D25 + D26 + D27 + D28 + D29 + D30 + D31;

            textBox35.Text = TH1.ToString();
            textBox36.Text = TS.ToString();           
            
            textBox3.Text = "0";
            textBox4.Text = "0";
            textBox5.Text = "0";
            textBox6.Text = "0";
            textBox7.Text = "0";
            textBox8.Text = "0";
            textBox9.Text = "0";
            textBox10.Text = "0";
            textBox11.Text = "0";
            textBox12.Text = "0";
            textBox13.Text = "0";
            textBox14.Text = "0";
            textBox15.Text = "0";
            textBox16.Text = "0";
            textBox17.Text = "0";
            textBox18.Text = "0";
            textBox19.Text = "0";
            textBox20.Text = "0";
            textBox21.Text = "0";
            textBox22.Text = "0";
            textBox23.Text = "0";
            textBox24.Text = "0";
            textBox25.Text = "0";
            textBox26.Text = "0";
            textBox27.Text = "0";
            textBox28.Text = "0";
            textBox29.Text = "0";
            textBox30.Text = "0";
            textBox31.Text = "0";
            textBox32.Text = "0";
            textBox33.Text = "0";


            
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            textBox1.Text = "-Enter your name-";
            comboBox1.Text = "-Select a Month-";
            label4.Text = "";
            label5.Text = "";
            label6.Text = "";
            label7.Text = "";
            label8.Text = "";
            label9.Text = "";
            label10.Text = "";
            label11.Text = "";
            label12.Text = "";
            label13.Text = "";
            label14.Text = "";
            label15.Text = "";
            label16.Text = "";
            label17.Text = "";
            label18.Text = "";
            label19.Text = "";
            label20.Text = "";
            label21.Text = "";
            label22.Text = "";
            label23.Text = "";
            label24.Text = "";
            label25.Text = "";
            label26.Text = "";
            label27.Text = "";
            label28.Text = "";
            label29.Text = "";
            label30.Text = "";
            label31.Text = "";
            label32.Text = "";
            label33.Text = "";
            label34.Text = "";
            textBox3.Text = "0";
            textBox4.Text = "0";
            textBox5.Text = "0";
            textBox6.Text = "0";
            textBox7.Text = "0";
            textBox8.Text = "0";
            textBox9.Text = "0";
            textBox10.Text = "0";
            textBox11.Text = "0";
            textBox12.Text = "0";
            textBox13.Text = "0";
            textBox14.Text = "0";
            textBox15.Text = "0";
            textBox16.Text = "0";
            textBox17.Text = "0";
            textBox18.Text = "0";
            textBox19.Text = "0";
            textBox20.Text = "0";
            textBox21.Text = "0";
            textBox22.Text = "0";
            textBox23.Text = "0";
            textBox24.Text = "0";
            textBox25.Text = "0";
            textBox26.Text = "0";
            textBox27.Text = "0";
            textBox28.Text = "0";
            textBox29.Text = "0";
            textBox30.Text = "0";
            textBox31.Text = "0";
            textBox32.Text = "0";
            textBox33.Text = "0";
            textBox2.Text = "0";            
            textBox35.Text = "0";
            textBox36.Text = "0";
            textBox3.Hide();
            textBox4.Hide();
            textBox5.Hide();
            textBox6.Hide();
            textBox7.Hide();
            textBox8.Hide();
            textBox9.Hide();
            textBox10.Hide();
            textBox11.Hide();
            textBox12.Hide();
            textBox13.Hide();
            textBox14.Hide();
            textBox15.Hide();
            textBox16.Hide();
            textBox17.Hide();
            textBox18.Hide();
            textBox19.Hide();
            textBox20.Hide();
            textBox21.Hide();
            textBox22.Hide();
            textBox23.Hide();
            textBox24.Hide();
            textBox25.Hide();
            textBox26.Hide();
            textBox27.Hide();
            textBox28.Hide();
            textBox29.Hide();
            textBox30.Hide();
            textBox31.Hide();
            textBox32.Hide();
            textBox33.Hide();
        }
        
        private void button1_Click_1(object sender, EventArgs e)
        {
            comboBox1.Text = comboBox1.Text;
            string Date = comboBox1.Text;
            textBox1.Text = textBox1.Text;
            string Name = textBox1.Text;

            if(Name == "-Enter your name-")
                MessageBox.Show("You must enter your name!", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            if (Name == "")
                MessageBox.Show("You must enter your name!", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            
             if (Date == "-Select a Month-")
                MessageBox.Show("You must set a date first!", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            
            
            if (comboBox1.SelectedIndex == 0)
            {
                
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "31";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox33.Text = "0";

                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();
                textBox33.Show();


            }
            if (comboBox1.SelectedIndex == 1)
            {
                
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "";
                label33.Text = "";
                label34.Text = "";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();

                textBox31.Hide();
                textBox32.Hide();
                textBox33.Hide();
                

                

            }
            if (comboBox1.SelectedIndex == 2)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "31";
                
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox33.Text = "0";
                
                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();
                textBox33.Show();                                                 
            }
            if (comboBox1.SelectedIndex == 3)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = ""; 
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0"; 
                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();
                

                textBox33.Hide();
            }
            if (comboBox1.SelectedIndex == 4)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "31";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox33.Text = "0";

                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();
                textBox33.Show(); 
            }
            if (comboBox1.SelectedIndex == 5)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();

                textBox33.Hide();
            }
            if (comboBox1.SelectedIndex == 6)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "31";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox33.Text = "0";

                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();
                textBox33.Show();
            }
            if (comboBox1.SelectedIndex == 7)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "31";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox33.Text = "0";

                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();
                textBox33.Show();
            }
            if (comboBox1.SelectedIndex == 8)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();


                textBox33.Hide();
            }
            if (comboBox1.SelectedIndex == 9)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "31";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox33.Text = "0";

                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();
                textBox33.Show();
            }
            if (comboBox1.SelectedIndex == 10)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();


                textBox33.Hide();
            }
            if (comboBox1.SelectedIndex == 11)
            {
                label4.Text = "1";
                label5.Text = "2";
                label6.Text = "3";
                label7.Text = "4";
                label8.Text = "5";
                label9.Text = "6";
                label10.Text = "7";
                label11.Text = "8";
                label12.Text = "9";
                label13.Text = "10";
                label14.Text = "11";
                label15.Text = "12";
                label16.Text = "13";
                label17.Text = "14";
                label18.Text = "15";
                label19.Text = "16";
                label20.Text = "17";
                label21.Text = "18";
                label22.Text = "19";
                label23.Text = "20";
                label24.Text = "21";
                label25.Text = "22";
                label26.Text = "23";
                label27.Text = "24";
                label28.Text = "25";
                label29.Text = "26";
                label30.Text = "27";
                label31.Text = "28";
                label32.Text = "29";
                label33.Text = "30";
                label34.Text = "31";
                textBox3.Text = "0";
                textBox4.Text = "0";
                textBox5.Text = "0";
                textBox6.Text = "0";
                textBox7.Text = "0";
                textBox8.Text = "0";
                textBox9.Text = "0";
                textBox10.Text = "0";
                textBox11.Text = "0";
                textBox12.Text = "0";
                textBox13.Text = "0";
                textBox14.Text = "0";
                textBox15.Text = "0";
                textBox16.Text = "0";
                textBox17.Text = "0";
                textBox18.Text = "0";
                textBox19.Text = "0";
                textBox20.Text = "0";
                textBox21.Text = "0";
                textBox22.Text = "0";
                textBox23.Text = "0";
                textBox24.Text = "0";
                textBox25.Text = "0";
                textBox26.Text = "0";
                textBox27.Text = "0";
                textBox28.Text = "0";
                textBox29.Text = "0";
                textBox30.Text = "0";
                textBox31.Text = "0";
                textBox32.Text = "0";
                textBox33.Text = "0";

                textBox3.Show();
                textBox4.Show();
                textBox5.Show();
                textBox6.Show();
                textBox7.Show();
                textBox8.Show();
                textBox9.Show();
                textBox10.Show();
                textBox11.Show();
                textBox12.Show();
                textBox13.Show();
                textBox14.Show();
                textBox15.Show();
                textBox16.Show();
                textBox17.Show();
                textBox18.Show();
                textBox19.Show();
                textBox20.Show();
                textBox21.Show();
                textBox22.Show();
                textBox23.Show();
                textBox24.Show();
                textBox25.Show();
                textBox26.Show();
                textBox27.Show();
                textBox28.Show();
                textBox29.Show();
                textBox30.Show();
                textBox31.Show();
                textBox32.Show();
                textBox33.Show();
            }
        }

        private void button2_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("Are you sure you want to Exit this application", "Exit Confirmation", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.No)
                this.Show();
            else
                this.Close();
        }

        private void textBox_MouseClick(object sender, MouseEventArgs e)
        {
            TextBox t = (TextBox)sender;
            t.Clear();
        }         
    }
}
